### ISSUE TITLE
open source the code, please

### ISSUE THREAD

**Issue by Morningstaripfy** [YanxingLiu/SAE-FSDet#1]
It's a great project i think after reading paper
I'm looking forward to the open source of your project.
When will you open source the code?

**Comment by YanxingLiu** [comment]
Thanks for your attention, I am sorting out my code. and the code will be released in two weeks.

**Comment by YanxingLiu** [comment]
> It's a great project i think after reading paper I'm looking forward to the open source of your project. When will you open source the code?

Thanks for your attention. I am sorting out my code and the code will be released in two weeks.

**Comment by YanxingLiu** [comment]
> It's a great project i think after reading paper I'm looking forward to the open source of your project. When will you open source the code?

Thanks for your time and attention, I have uploaded data splits, training and testing code in this repo. I hope this will help you.
