### ISSUE TITLE
How to do set up and train on a custom dataset

### ISSUE THREAD

**Issue by MarineMehrabyan** [YanxingLiu/SAE-FSDet#10]
In order to understand how to formalize the position and change the variables in the code, depending on the classes on which the training will take place, I first tried to train the model on three Dior classes and then do fine-tuning on another class (but it is again from Dior). It worked.

        Now I use the same principle to train the data of my class, I just put the images and labels in the same Dior folders, and in these folders I deleted those old original photos and labels of the Dior classes. And it tells me that there is no such class in Dior. But in the splits I changed the names of the classes, and left only the name of my class. 

        Based on this, I realized that it still stores information about the names of the Dior classes somewhere. Where does it get information about which classes are contained in Dior?

**Comment by YanxingLiu** [comment]
Sorry for our late reply. Our code is based on mmdetection and mmfewshot. You can refer to the document of mmdetection to know the basics of dataset construction. https://mmdetection.readthedocs.io/en/v2.26.0/tutorials/customize_dataset.html

**Comment by MarineMehrabyan** [comment]
Thank you for your response! I had already customized the dataset as described in the mmdetection documentation and completed that part successfully

Also, what results did you get on the DIOR dataset? I’m seeing a relatively low performance (around 30% mAP) after fine-tuning and would appreciate any insights you might have on improving this.

**Comment by YanxingLiu** [comment]
> Thank you for your response! I had already customized the dataset as described in the mmdetection documentation and completed that part successfully
> 
> Also, what results did you get on the DIOR dataset? I’m seeing a relatively low performance (around 30% mAP) after fine-tuning and would appreciate any insights you might have on improving this.

Could you give more detailed description? You can check the number of classes and benchmark splits in data folder. Few-shot learning is sensitive to the sample selection. If you follow the instructions of README.md, the performance should not be much lower.

**Comment by MarineMehrabyan** [comment]
So I say that it is on your DIOR dataset that I get low results, completely following your steps. Why don't you want to tell the results (i.e. mAP) that you got? I'm interested in comparing them.

**Comment by YanxingLiu** [comment]
> So I say that it is on your DIOR dataset that I get low results, completely following your steps. Why don't you want to tell the results (i.e. mAP) that you got? I'm interested in comparing them.

So can you give more description? I don't know exactly how much performance you're achieving if you don't provide me with detailed split settings and shot-setting. You can provide a training log to better identify problems.

**Comment by MarineMehrabyan** [comment]
I am not saying that the results were bad as a result of a mistake, first of all I should say that the DIOR data set is poorly labeled. Therefore, even the base train will be bad, that's one thing.
secondly, I noticed that when doing base train, you transfer images that also contain novel class labels, is that correct, but that's how we make it background, and then during fine tuning, the error will increase.
I took them out and tried that, but the result is only bad.
I think the problem is with the judgment.

I have just started researching this approach, I would greatly appreciate it if you could give me some pointers.

now I want to write my project, based on your project, what advice would you give me, what steps should I start with?

thank you for your time and project.

**Comment by YanxingLiu** [comment]
> I am not saying that the results were bad as a result of a mistake, first of all I should say that the DIOR data set is poorly labeled. Therefore, even the base train will be bad, that's one thing. secondly, I noticed that when doing base train, you transfer images that also contain novel class labels, is that correct, but that's how we make it background, and then during fine tuning, the error will increase. I took them out and tried that, but the result is only bad. I think the problem is with the judgment.
> 
> I have just started researching this approach, I would greatly appreciate it if you could give me some pointers.
> 
> now I want to write my project, based on your project, what advice would you give me, what steps should I start with?
> 
> thank you for your time and project.

1. Maybe some errors in your base training, in my practice, the mAP of base training is about 70 or higher. Some other works like P-CNN also demonstrate similar results. 
2. In the base-training phase, we tend to train on a large-scale base dataset, however, in the actual training process, the base dataset often inevitably contains some novel instances that are not labeled as foregrounds.In the previous approach, these novel targets would be directly judged as the background, yet in the fine-tuning phase, these targets belong toforeground, which we call the labeling inconsistency phenomenon.Therefore, we introduce an LCC to alleviate this phenomenon, the LCC judges the targets to be in theothers category in the base training phase, and in the fine-tuning phase, all the targets in theothers category are further labeled as foreground. Categorization. More details can be found in our paper.

**Comment by YanxingLiu** [comment]
> I am not saying that the results were bad as a result of a mistake, first of all I should say that the DIOR data set is poorly labeled. Therefore, even the base train will be bad, that's one thing. secondly, I noticed that when doing base train, you transfer images that also contain novel class labels, is that correct, but that's how we make it background, and then during fine tuning, the error will increase. I took them out and tried that, but the result is only bad. I think the problem is with the judgment.
> 
> I have just started researching this approach, I would greatly appreciate it if you could give me some pointers.
> 
> now I want to write my project, based on your project, what advice would you give me, what steps should I start with?
> 
> thank you for your time and project.

As for new research, I suggest you start with the official mmfewshot implementation, which is much more elegant and easy to understand for newbies. After you finish learning mmfewshot you can simply modify it based on my method.

**Comment by MarineMehrabyan** [comment]
Thank you so much
