### ISSUE TITLE
How should val.txt, trainval.txt files be in NWPU VHR-10 dataset?

### ISSUE THREAD

**Issue by MarineMehrabyan** [YanxingLiu/SAE-FSDet#12]
How should val.txt, trainval.txt files be in NWPU VHR-10 dataset?

**Comment by YanxingLiu** [comment]
> How should val.txt, trainval.txt files be in NWPU VHR-10 dataset?

In NWPU VHR-10, we train our model based on train.txt, and test our model  based on test.txt

**Comment by YanxingLiu** [comment]
The layout is similar to this:
<img width="429" alt="image" src="https://github.com/user-attachments/assets/c0265730-159a-432b-9c41-a721aaace14a">

**Comment by MarineMehrabyan** [comment]
but there is no trainval.txt and val.txt

**Comment by YanxingLiu** [comment]
> but there is no trainval.txt and val.txt

simularly, train.txt plays the role of specify training data, and test.txt plays the role of specify testing data
