### ISSUE TITLE
Some errors about mmcv version

### ISSUE THREAD

**Issue by PiPiNam** [YanxingLiu/SAE-FSDet#2]
As you list in the readme file, the version of mmcv you recommend is1.6.0 and torch version=2.0.0. 

However, there is conflict with these two version. torch=2.0.0 cannot compatible with mmcv=1.6.0.

So I just install mmcv=2.0.0, but when I run "python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py" to train the model, error shows 

Traceback (most recent call last):
  File "tools/detection/train.py", line 13, in <module>
    from mmcv import Config, DictAction
ImportError: cannot import name 'Config' from 'mmcv' (/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/__init__.py)

I don't know how to resolve this problem, I would be appreciated if you can help me to deal with this error!

**Comment by YanxingLiu** [comment]
> As you list in the readme file, the version of mmcv you recommend is1.6.0 and torch version=2.0.0.
> 
> However, there is conflict with these two version. torch=2.0.0 cannot compatible with mmcv=1.6.0.
> 
> So I just install mmcv=2.0.0, but when I run "python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py" to train the model, error shows
> 
> Traceback (most recent call last): File "tools/detection/train.py", line 13, in from mmcv import Config, DictAction ImportError: cannot import name 'Config' from 'mmcv' (/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/**init**.py)
> 
> I don't know how to resolve this problem, I would be appreciated if you can help me to deal with this error!

mmcv 2.0 is not compatible with mmcv1.x, all of my codes are based on mmcv 1.x . I was compile my mmcv 1.16.0 from source. I recommend you change the torchversion to compatible with mmcv 1.x. Hope this will help you!

**Comment by PiPiNam** [comment]
> > As you list in the readme file, the version of mmcv you recommend is1.6.0 and torch version=2.0.0.
> > However, there is conflict with these two version. torch=2.0.0 cannot compatible with mmcv=1.6.0.
> > So I just install mmcv=2.0.0, but when I run "python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py" to train the model, error shows
> > Traceback (most recent call last): File "tools/detection/train.py", line 13, in from mmcv import Config, DictAction ImportError: cannot import name 'Config' from 'mmcv' (/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/**init**.py)
> > I don't know how to resolve this problem, I would be appreciated if you can help me to deal with this error!
> 
> mmcv 2.0 is not compatible with mmcv1.x, all of my codes are based on mmcv 1.x . I was compile my mmcv 1.6.0 from source. I recommend you change the torchversion to compatible with mmcv 1.x. Hope this will help you!

Thanks for your reply! I follow your READEME to do installation again and fix the issue mentioned above.

But when I try to train the model and run the **code python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py** an error shows as below:

(SAE-FSDet) linan@gpu2:/mnt/data/linan/SAE-FSDet$ python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_20shot_finetuning.py 
apex is not installed
apex is not installed
Traceback (most recent call last):
  File "tools/detection/train.py", line 168, in <module>
    train()
  File "tools/detection/train.py", line 87, in train
    cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
  File "/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/utils/config.py", line 596, in dump
    f.write(self.pretty_text)
  File "/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text
    text, _ = FormatCode(text, style_config=yapf_style, verify=True)
TypeError: FormatCode() got an unexpected keyword argument 'verify'

![image](https://github.com/YanxingLiu/SAE-FSDet/assets/56286935/590480e4-bc95-4c9a-9699-1f176d47feed)

I would be appreciated if you can help me to deal with this error!

**Comment by YanxingLiu** [comment]
> > > As you list in the readme file, the version of mmcv you recommend is1.6.0 and torch version=2.0.0.
> > > However, there is conflict with these two version. torch=2.0.0 cannot compatible with mmcv=1.6.0.
> > > So I just install mmcv=2.0.0, but when I run "python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py" to train the model, error shows
> > > Traceback (most recent call last): File "tools/detection/train.py", line 13, in from mmcv import Config, DictAction ImportError: cannot import name 'Config' from 'mmcv' (/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/**init**.py)
> > > I don't know how to resolve this problem, I would be appreciated if you can help me to deal with this error!
> > 
> > 
> > mmcv 2.0 is not compatible with mmcv1.x, all of my codes are based on mmcv 1.x . I was compile my mmcv 1.6.0 from source. I recommend you change the torchversion to compatible with mmcv 1.x. Hope this will help you!
> 
> Thanks for your reply! I follow your READEME to do installation again and fix the issue mentioned above.
> 
> But when I try to train the model and run the **code python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py** an error shows as below:
> 
> (SAE-FSDet) linan@gpu2:/mnt/data/linan/SAE-FSDet$ python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_20shot_finetuning.py apex is not installed apex is not installed Traceback (most recent call last): File "tools/detection/train.py", line 168, in train() File "tools/detection/train.py", line 87, in train cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config))) File "/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/utils/config.py", line 596, in dump f.write(self.pretty_text) File "/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text text, _ = FormatCode(text, style_config=yapf_style, verify=True) TypeError: FormatCode() got an unexpected keyword argument 'verify'
> 
> ![image](https://private-user-images.githubusercontent.com/56286935/347323657-590480e4-bc95-4c9a-9699-1f176d47feed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDM5NDAsIm5iZiI6MTcyMDYwMzY0MCwicGF0aCI6Ii81NjI4NjkzNS8zNDczMjM2NTctNTkwNDgwZTQtYmM5NS00YzlhLTk2OTktMWYxNzZkNDdmZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA5MjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NjhlZTA5YzIyMDBmODRhYTBkMmYwYzg5NzU4YTZkYTVmZjFhYmRjMWQ5NGMzMDdkOTUxNmE3OGRlYjkxODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yJgduXgte9xNiJp3AGtp40yjMUWWbBUw0Qxb7HC0oM8)
> 
> I would be appreciated if you can help me to deal with this error!

you could simply delete this argument "verify",

**Comment by PiPiNam** [comment]
> > > > As you list in the readme file, the version of mmcv you recommend is1.6.0 and torch version=2.0.0.
> > > > However, there is conflict with these two version. torch=2.0.0 cannot compatible with mmcv=1.6.0.
> > > > So I just install mmcv=2.0.0, but when I run "python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py" to train the model, error shows
> > > > Traceback (most recent call last): File "tools/detection/train.py", line 13, in from mmcv import Config, DictAction ImportError: cannot import name 'Config' from 'mmcv' (/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/**init**.py)
> > > > I don't know how to resolve this problem, I would be appreciated if you can help me to deal with this error!
> > > 
> > > 
> > > mmcv 2.0 is not compatible with mmcv1.x, all of my codes are based on mmcv 1.x . I was compile my mmcv 1.6.0 from source. I recommend you change the torchversion to compatible with mmcv 1.x. Hope this will help you!
> > 
> > 
> > Thanks for your reply! I follow your READEME to do installation again and fix the issue mentioned above.
> > But when I try to train the model and run the **code python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py** an error shows as below:
> > (SAE-FSDet) linan@gpu2:/mnt/data/linan/SAE-FSDet$ python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_20shot_finetuning.py apex is not installed apex is not installed Traceback (most recent call last): File "tools/detection/train.py", line 168, in train() File "tools/detection/train.py", line 87, in train cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config))) File "/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/utils/config.py", line 596, in dump f.write(self.pretty_text) File "/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text text, _ = FormatCode(text, style_config=yapf_style, verify=True) TypeError: FormatCode() got an unexpected keyword argument 'verify'
> > ![image](https://private-user-images.githubusercontent.com/56286935/347323657-590480e4-bc95-4c9a-9699-1f176d47feed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDM5NDAsIm5iZiI6MTcyMDYwMzY0MCwicGF0aCI6Ii81NjI4NjkzNS8zNDczMjM2NTctNTkwNDgwZTQtYmM5NS00YzlhLTk2OTktMWYxNzZkNDdmZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA5MjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NjhlZTA5YzIyMDBmODRhYTBkMmYwYzg5NzU4YTZkYTVmZjFhYmRjMWQ5NGMzMDdkOTUxNmE3OGRlYjkxODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yJgduXgte9xNiJp3AGtp40yjMUWWbBUw0Qxb7HC0oM8)
> > I would be appreciated if you can help me to deal with this error!
> 
> you could simply delete this argument "verify",

Thank you so much for your reply!  I found that the problem caues by the version of yapf, and the best version of yapf=0.40.1. 

You can test it and add the version striction to requirements.txt for convenience.

**Comment by YanxingLiu** [comment]
> > > > > As you list in the readme file, the version of mmcv you recommend is1.6.0 and torch version=2.0.0.
> > > > > However, there is conflict with these two version. torch=2.0.0 cannot compatible with mmcv=1.6.0.
> > > > > So I just install mmcv=2.0.0, but when I run "python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py" to train the model, error shows
> > > > > Traceback (most recent call last): File "tools/detection/train.py", line 13, in from mmcv import Config, DictAction ImportError: cannot import name 'Config' from 'mmcv' (/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/**init**.py)
> > > > > I don't know how to resolve this problem, I would be appreciated if you can help me to deal with this error!
> > > > 
> > > > 
> > > > mmcv 2.0 is not compatible with mmcv1.x, all of my codes are based on mmcv 1.x . I was compile my mmcv 1.6.0 from source. I recommend you change the torchversion to compatible with mmcv 1.x. Hope this will help you!
> > > 
> > > 
> > > Thanks for your reply! I follow your READEME to do installation again and fix the issue mentioned above.
> > > But when I try to train the model and run the **code python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py** an error shows as below:
> > > (SAE-FSDet) linan@gpu2:/mnt/data/linan/SAE-FSDet$ python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_20shot_finetuning.py apex is not installed apex is not installed Traceback (most recent call last): File "tools/detection/train.py", line 168, in train() File "tools/detection/train.py", line 87, in train cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config))) File "/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/utils/config.py", line 596, in dump f.write(self.pretty_text) File "/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text text, _ = FormatCode(text, style_config=yapf_style, verify=True) TypeError: FormatCode() got an unexpected keyword argument 'verify'
> > > ![image](https://private-user-images.githubusercontent.com/56286935/347323657-590480e4-bc95-4c9a-9699-1f176d47feed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDM5NDAsIm5iZiI6MTcyMDYwMzY0MCwicGF0aCI6Ii81NjI4NjkzNS8zNDczMjM2NTctNTkwNDgwZTQtYmM5NS00YzlhLTk2OTktMWYxNzZkNDdmZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA5MjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NjhlZTA5YzIyMDBmODRhYTBkMmYwYzg5NzU4YTZkYTVmZjFhYmRjMWQ5NGMzMDdkOTUxNmE3OGRlYjkxODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yJgduXgte9xNiJp3AGtp40yjMUWWbBUw0Qxb7HC0oM8)
> > > I would be appreciated if you can help me to deal with this error!
> > 
> > 
> > you could simply delete this argument "verify",
> 
> Thank you so much for your reply! I found that the problem caues by the version of yapf, and the best version of yapf=0.40.1.
> 
> You can test it and add the version striction to requirements.txt for convenience.

Thanks for your suggestion, I will add it later.

**Comment by yyygh007** [comment]
i follow readme to complete the torch installation, but the mmcv-full==1.6.0 installation have some problems:
ERROR: Failed building wheel for mmcv-full
![ad72086d37223746765b1f8f6429ced](https://github.com/user-attachments/assets/394060b0-0e4f-447a-949e-cc8ae9717c18)
![image](https://github.com/user-attachments/assets/4e41551c-643d-42a6-a492-c4bb018ffcdd)

**Comment by yyygh007** [comment]
> > > > > As you list in the readme file, the version of mmcv you recommend is1.6.0 and torch version=2.0.0.
> > > > > However, there is conflict with these two version. torch=2.0.0 cannot compatible with mmcv=1.6.0.
> > > > > So I just install mmcv=2.0.0, but when I run "python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py" to train the model, error shows
> > > > > Traceback (most recent call last): File "tools/detection/train.py", line 13, in from mmcv import Config, DictAction ImportError: cannot import name 'Config' from 'mmcv' (/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/**init**.py)
> > > > > I don't know how to resolve this problem, I would be appreciated if you can help me to deal with this error!
> > > > 
> > > > 
> > > > mmcv 2.0 is not compatible with mmcv1.x, all of my codes are based on mmcv 1.x . I was compile my mmcv 1.6.0 from source. I recommend you change the torchversion to compatible with mmcv 1.x. Hope this will help you!
> > > 
> > > 
> > > Thanks for your reply! I follow your READEME to do installation again and fix the issue mentioned above.
> > > But when I try to train the model and run the **code python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_base-training.py** an error shows as below:
> > > (SAE-FSDet) linan@gpu2:/mnt/data/linan/SAE-FSDet$ python tools/detection/train.py configs/detection/SAE-FSDet/dior/split1/SAE-FSDet_r101_fpn_dior-split1_20shot_finetuning.py apex is not installed apex is not installed Traceback (most recent call last): File "tools/detection/train.py", line 168, in train() File "tools/detection/train.py", line 87, in train cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config))) File "/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/utils/config.py", line 596, in dump f.write(self.pretty_text) File "/home/linan/miniconda3/envs/SAE-FSDet/lib/python3.8/site-packages/mmcv/utils/config.py", line 508, in pretty_text text, _ = FormatCode(text, style_config=yapf_style, verify=True) TypeError: FormatCode() got an unexpected keyword argument 'verify'
> > > ![image](https://private-user-images.githubusercontent.com/56286935/347323657-590480e4-bc95-4c9a-9699-1f176d47feed.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MDM5NDAsIm5iZiI6MTcyMDYwMzY0MCwicGF0aCI6Ii81NjI4NjkzNS8zNDczMjM2NTctNTkwNDgwZTQtYmM5NS00YzlhLTk2OTktMWYxNzZkNDdmZWVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDA5MjcyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1NjhlZTA5YzIyMDBmODRhYTBkMmYwYzg5NzU4YTZkYTVmZjFhYmRjMWQ5NGMzMDdkOTUxNmE3OGRlYjkxODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yJgduXgte9xNiJp3AGtp40yjMUWWbBUw0Qxb7HC0oM8)
> > > I would be appreciated if you can help me to deal with this error!
> > 
> > 
> > you could simply delete this argument "verify",
> 
> Thank you so much for your reply! I found that the problem caues by the version of yapf, and the best version of yapf=0.40.1.
> 
> You can test it and add the version striction to requirements.txt for convenience.

Hello, have you successfully run through the code, and would like to ask some questions
my email：2500327025@qq.com
