### ISSUE TITLE
DIOR dataset cannot be opened

### ISSUE THREAD

**Issue by qjh666888** [YanxingLiu/SAE-FSDet#4]
http://[www.escience.cn](http://www.escience.cn/people/JunweiHan/DIOR.html)/people/JunweiHan/DIOR.html   cannot be opened

**Comment by YanxingLiu** [comment]
> **[qjh666888](/qjh666888) ** commented
It seems that the original website of DIOR can not be accessed. You can find DIOR dataset in other website like AI studio and so on.
