### ISSUE TITLE
install mmcv-full==1.6.0 error

### ISSUE THREAD

**Issue by yyygh007** [YanxingLiu/SAE-FSDet#5]
pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118
然后torch版本和mim install mmcv-full==1.6.0的版本好像不对应， 会出现：ERROR: Failed building wheel for mmcv-full的问题

**Comment by YanxingLiu** [comment]
可以试试pip安装，我当初安装mmcv-full的时候这个版本是可以的，可能mim有更新。mmcv-full和 torch的版本可以不用限制这么死，不报错应该就可以运行。

**Comment by YanxingLiu** [comment]
> pip install torch==2.0.0 torchvision==0.15.1 torchaudio==2.0.1 --index-url https://download.pytorch.org/whl/cu118 然后torch版本和mim install mmcv-full==1.6.0的版本好像不对应， 会出现：ERROR: Failed building wheel for mmcv-full的问题


可以试试pip安装，我当初安装mmcv-full的时候这个版本是可以的，可能mim有更新。mmcv-full和 torch的版本可以不用限制这么死，版本变化不大的话应该问题不大。

**Comment by yyygh007** [comment]
If I download mmcv==2.0 and above according to the version required by the official website, I find that many mmcv module imports will have errors
![image](https://github.com/user-attachments/assets/23fe2614-6666-4861-a9a5-f875ce08102c)
![image](https://github.com/user-attachments/assets/76cd909f-58bc-41ed-91a7-4858f364dd73)

**Comment by QuanKunNguyen2711** [comment]
how can you resolve this @yyygh007

**Comment by yyygh007** [comment]
pip install mmcv-full==1.x -f https://download.openmmlab.com/mmcv/dist/cu117/torch1.13.0/index.html&nbsp;我安装了1.7.1之后可以使用了，需要注意你的torch cuda也对应



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "YanxingLiu/SAE-FSDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2025年8月17日(星期天) 晚上10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [YanxingLiu/SAE-FSDet] install mmcv-full==1.6.0 error (Issue #5)



QuanKunNguyen2711 left a comment (YanxingLiu/SAE-FSDet#5)
 
how can you resolve this @yyygh007
