### ISSUE TITLE
diro datasets

### ISSUE THREAD

**Issue by yyygh007** [YanxingLiu/SAE-FSDet#6]
Hello author, did the images in the JPEGImages in your dior dataset directory merge the images in the JPEGImages-test file and the JPEGImages-train file together?

**Comment by YanxingLiu** [comment]
> Hello author, did the images in the JPEGImages in your dior dataset directory merge the images in the JPEGImages-test file and the JPEGImages-train file together?

Yes, sorry to mention this, I will add it to readme later.

**Comment by yyygh007** [comment]
Thank you for your reply！
