### ISSUE TITLE
关于mmcv版本出现问题

### ISSUE THREAD

**Issue by Radiantzy** [YanxingLiu/SAE-FSDet#8]
您的论文代码上写的版本无法复现，会显示mmcv-full安装不上，请问您当时进行编译工作的时候的环境是您列写的环境吗，如果不是也请邮件告知

**Comment by YanxingLiu** [comment]
You can refer to previous issue about mmcv version like https://github.com/YanxingLiu/SAE-FSDet/issues/2 and so on

**Comment by YanxingLiu** [comment]
You can refer to previous issue about mmcv version like https://github.com/YanxingLiu/SAE-FSDet/issues/2 and so on

**Comment by YanxingLiu** [comment]
> 您的论文代码上写的版本无法复现，会显示mmcv-full安装不上，请问您当时进行编译工作的时候的环境是您列写的环境吗，如果不是也请邮件告知，我的邮箱是[3605859842@qq.com](mailto:3605859842@qq.com)

You can refer to previous issue about mmcv version like https://github.com/YanxingLiu/SAE-FSDet/issues/2 and so on

**Comment by Radiantzy** [comment]
python packages
Python 3.8
torch 1.8.1
mmcv-full 1.6.0
mmdet 2.27.0
mmcls 0.25.0
yapf 0.40.1
CUDA 10.2

**Comment by Radiantzy** [comment]
以上环境配置成功解决问题，会提示  fatal: not a git repository (or any of the parent directories): .git
再解决一下就好了
