### ISSUE TITLE
关于mmfewshot文件均无法正确import

### ISSUE THREAD

**Issue by Radiantzy** [YanxingLiu/SAE-FSDet#9]
![image](https://github.com/user-attachments/assets/54f9d950-c9de-4224-8cfe-27c8cc023e34)
请问这种情况下应该怎么解决？

**Comment by YanxingLiu** [comment]
you can resolve the problem by running pip install -v -e . 
<img width="508" alt="image" src="https://github.com/user-attachments/assets/f6e984d0-eece-42ed-9d84-af4874d20971">

**Comment by Radiantzy** [comment]
感谢您的回复，问题已经成功解决，重新装了环境试了一下，后面的报错与cuda版本无太大关系，目前试了cuda10.2/11.7/11.8均可正常进行代码的运行，mmcv-full的版本不需要强制1.6.0，（并且如果强制1.6.0似乎只能在cuda10.2版本运行），新版的mmcv-full也可以运行，只需要保证torch在1.xx下即可，mmdet和mmcls也无另外报错。

**Comment by Radiantzy** [comment]
但是我遇到了新问题，目前还没有解决，请问您有没有更好的解决办法？
ValueError: need at least one array to concatenate
![image](https://github.com/user-attachments/assets/fbf650cd-b2d0-4652-8244-7d91d1aa872c)
